import { BaseStackPlugin } from '../base-stack';
import { GeneratorOptions } from '@/generator';
import path from 'path';
import fs from 'fs';

export class PythonStackPlugin extends BaseStackPlugin {
  name = 'python';
  aliases = ['py'];

  detect(cwd: string): boolean {
    if (fs.existsSync(path.join(cwd, 'requirements.txt')) || 
        fs.existsSync(path.join(cwd, 'setup.py')) ||
        fs.existsSync(path.join(cwd, 'pyproject.toml'))) {
      return true;
    }
    return false;
  }

  async generateSkeleton(opts: GeneratorOptions): Promise<void> {
    const pkgName = this.toPkgName(opts.projectName);

    // pyproject.toml
    const pyproject = `
[project]
name = "${opts.projectName}"
version = "0.1.0"
description = "A Python project generated by SpecKit-BMAD"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[project.optional-dependencies]
test = ["pytest"]

[project.scripts]
${pkgName} = "${pkgName}.__main__:main"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["tests"]
`.trim();
    this.writeFile(path.join(opts.projectDir, 'pyproject.toml'), pyproject, opts.dryRun);

    // README.md
    const readme = `
# ${opts.projectName}

Generated by SpecKit-BMAD.

## Installation

\`\`\`bash
pip install -e .
\`\`\`

## Usage

\`\`\`bash
${pkgName} --help
\`\`\`
`.trim();
    this.writeFile(path.join(opts.projectDir, 'README.md'), readme, opts.dryRun);

    // .gitignore
    const gitignore = `
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg
.venv
venv/
ENV/
env/
ENV/
`.trim();
    this.writeFile(path.join(opts.projectDir, '.gitignore'), gitignore, opts.dryRun);

    // src/pkg/__init__.py
    this.writeFile(path.join(opts.projectDir, 'src', pkgName, '__init__.py'), '', opts.dryRun);

    // src/pkg/__main__.py
    const mainPy = `
import sys

def main():
    """Main entry point for the application."""
    print("Hello from ${opts.projectName}!")
    if "--help" in sys.argv:
        print("usage: ${pkgName} [options]")
        sys.exit(0)
    sys.exit(0)

if __name__ == "__main__":
    main()
`.trim();
    this.writeFile(path.join(opts.projectDir, 'src', pkgName, '__main__.py'), mainPy, opts.dryRun);

    // tests/__init__.py
    this.writeFile(path.join(opts.projectDir, 'tests', '__init__.py'), '', opts.dryRun);

    // tests/test_basic.py
    const testPy = `
def test_basic():
    assert 1 == 1

def test_import():
    # Installed in editable mode, so import directly
    import ${pkgName}
    assert ${pkgName} is not None
`.trim();
    this.writeFile(path.join(opts.projectDir, 'tests', 'test_basic.py'), testPy, opts.dryRun);
  }

  getRunCommand(cwd: string, script?: string): string {
    if (script) return `python ${script}`;
    // 尝试查找入口
    const srcDir = path.join(cwd, 'src');
    if (fs.existsSync(srcDir)) {
      const pkgName = this.toPkgName(path.basename(cwd));
      // 优先使用 -m 运行模块
      return `python -m ${pkgName}`;
    }
    return 'python main.py';
  }

  getTestCommand(cwd: string): string {
    return 'pytest';
  }
}
