/**
 * Python Stack Plugin Tests
 *
 * Tests for Python project detection and scaffolding
 */

import { PythonStackPlugin } from '@/plugins/stack-python';
import * as fs from 'fs';
import * as path from 'path';
import {
  createTempProjectDir,
  cleanupTempDir,
  createMockGeneratorOptions,
  createTestFile,
  assertFileExists,
  assertFileContains,
  assertFileNotExists,
  readTestFile,
  fixtures,
} from './plugin-test-utils';

describe('PythonStackPlugin', () => {
  let plugin: PythonStackPlugin;
  let tmpDir: string;

  beforeEach(() => {
    plugin = new PythonStackPlugin();
    tmpDir = createTempProjectDir('py-plugin-test-');
  });

  afterEach(() => {
    cleanupTempDir(tmpDir);
  });

  describe('properties', () => {
    it('should have correct name', () => {
      expect(plugin.name).toBe('python');
    });

    it('should have correct aliases', () => {
      expect(plugin.aliases).toEqual(['py']);
    });
  });

  describe('detect()', () => {
    it('should return true when requirements.txt exists', () => {
      createTestFile(tmpDir, 'requirements.txt', fixtures.python.requirementsTxt);
      expect(plugin.detect(tmpDir)).toBe(true);
    });

    it('should return true when setup.py exists', () => {
      createTestFile(tmpDir, 'setup.py', fixtures.python.setupPy);
      expect(plugin.detect(tmpDir)).toBe(true);
    });

    it('should return true when pyproject.toml exists', () => {
      createTestFile(tmpDir, 'pyproject.toml', fixtures.python.pyprojectToml);
      expect(plugin.detect(tmpDir)).toBe(true);
    });

    it('should return false when no Python files exist', () => {
      expect(plugin.detect(tmpDir)).toBe(false);
    });
  });

  describe('generateSkeleton()', () => {
    it('should create pyproject.toml with correct project metadata', async () => {
      const opts = createMockGeneratorOptions({
        projectDir: tmpDir,
        projectName: 'my-python-app',
      });

      await plugin.generateSkeleton(opts);

      const pyprojectPath = path.join(tmpDir, 'pyproject.toml');
      assertFileExists(pyprojectPath);
      assertFileContains(pyprojectPath, 'name = "my-python-app"');
      assertFileContains(pyprojectPath, 'version = "0.1.0"');
      assertFileContains(pyprojectPath, 'requires-python = ">=3.8"');
    });

    it('should create pyproject.toml with correct script entry point', async () => {
      const opts = createMockGeneratorOptions({
        projectDir: tmpDir,
        projectName: 'my-awesome-tool',
      });

      await plugin.generateSkeleton(opts);

      const content = readTestFile(tmpDir, 'pyproject.toml');
      // Package name should be converted: my-awesome-tool -> my_awesome_tool
      expect(content).toContain('my_awesome_tool = "my_awesome_tool.__main__:main"');
    });

    it('should create README.md with project name', async () => {
      const opts = createMockGeneratorOptions({
        projectDir: tmpDir,
        projectName: 'cool-project',
      });

      await plugin.generateSkeleton(opts);

      const readmePath = path.join(tmpDir, 'README.md');
      assertFileExists(readmePath);
      assertFileContains(readmePath, '# cool-project');
      assertFileContains(readmePath, 'Generated by SpecKit-BMAD');
    });

    it('should create .gitignore with Python patterns', async () => {
      const opts = createMockGeneratorOptions({ projectDir: tmpDir });
      await plugin.generateSkeleton(opts);

      const gitignorePath = path.join(tmpDir, '.gitignore');
      assertFileExists(gitignorePath);
      assertFileContains(gitignorePath, '__pycache__/');
      assertFileContains(gitignorePath, '*.py[cod]');
      assertFileContains(gitignorePath, '.venv');
    });

    it('should create src/{pkg_name}/__init__.py as empty file', async () => {
      const opts = createMockGeneratorOptions({
        projectDir: tmpDir,
        projectName: 'test-pkg',
      });

      await plugin.generateSkeleton(opts);

      const initPath = path.join(tmpDir, 'src', 'test_pkg', '__init__.py');
      assertFileExists(initPath);
      const content = fs.readFileSync(initPath, 'utf-8');
      expect(content).toBe('');
    });

    it('should create src/{pkg_name}/__main__.py with main function', async () => {
      const opts = createMockGeneratorOptions({
        projectDir: tmpDir,
        projectName: 'my-app',
      });

      await plugin.generateSkeleton(opts);

      const mainPath = path.join(tmpDir, 'src', 'my_app', '__main__.py');
      assertFileExists(mainPath);
      assertFileContains(mainPath, 'def main():');
      assertFileContains(mainPath, 'Hello from my-app');
      assertFileContains(mainPath, 'if __name__ == "__main__":');
    });

    it('should create tests/__init__.py as empty file', async () => {
      const opts = createMockGeneratorOptions({ projectDir: tmpDir });
      await plugin.generateSkeleton(opts);

      const testInitPath = path.join(tmpDir, 'tests', '__init__.py');
      assertFileExists(testInitPath);
      const content = fs.readFileSync(testInitPath, 'utf-8');
      expect(content).toBe('');
    });

    it('should create tests/test_basic.py with example tests', async () => {
      const opts = createMockGeneratorOptions({
        projectDir: tmpDir,
        projectName: 'my-lib',
      });

      await plugin.generateSkeleton(opts);

      const testPath = path.join(tmpDir, 'tests', 'test_basic.py');
      assertFileExists(testPath);
      assertFileContains(testPath, 'def test_basic():');
      assertFileContains(testPath, 'def test_import():');
      assertFileContains(testPath, 'import my_lib');
    });

    it('should convert project name to valid package name', async () => {
      const opts = createMockGeneratorOptions({
        projectDir: tmpDir,
        projectName: 'My-Cool Project!',
      });

      await plugin.generateSkeleton(opts);

      // Should convert to: My_CoolProject (remove spaces and !, convert - to _)
      const pkgName = 'My_CoolProject';
      const initPath = path.join(tmpDir, 'src', pkgName, '__init__.py');
      assertFileExists(initPath);
    });

    it('should respect dryRun option', async () => {
      const opts = createMockGeneratorOptions({
        projectDir: tmpDir,
        dryRun: true,
      });

      await plugin.generateSkeleton(opts);

      // No files should be created
      assertFileNotExists(path.join(tmpDir, 'pyproject.toml'));
      assertFileNotExists(path.join(tmpDir, 'README.md'));
      assertFileNotExists(path.join(tmpDir, '.gitignore'));
    });

    it('should create all expected files', async () => {
      const opts = createMockGeneratorOptions({
        projectDir: tmpDir,
        projectName: 'test-project',
      });

      await plugin.generateSkeleton(opts);

      // Verify all 7 files are created
      assertFileExists(path.join(tmpDir, 'pyproject.toml'));
      assertFileExists(path.join(tmpDir, 'README.md'));
      assertFileExists(path.join(tmpDir, '.gitignore'));
      assertFileExists(path.join(tmpDir, 'src', 'test_project', '__init__.py'));
      assertFileExists(path.join(tmpDir, 'src', 'test_project', '__main__.py'));
      assertFileExists(path.join(tmpDir, 'tests', '__init__.py'));
      assertFileExists(path.join(tmpDir, 'tests', 'test_basic.py'));
    });
  });

  describe('toPkgName()', () => {
    it('should convert hyphens to underscores', () => {
      // Access protected method via any cast for testing
      const result = (plugin as any).toPkgName('my-project');
      expect(result).toBe('my_project');
    });

    it('should remove spaces', () => {
      const result = (plugin as any).toPkgName('My Project');
      expect(result).toBe('MyProject');
    });

    it('should convert multiple hyphens to single underscore', () => {
      const result = (plugin as any).toPkgName('my--project');
      expect(result).toBe('my_project');
    });

    it('should remove special characters', () => {
      const result = (plugin as any).toPkgName('my-project!@#');
      expect(result).toBe('my_project');
    });
  });

  describe('getRunCommand()', () => {
    it('should return python with script when script is provided', () => {
      const result = plugin.getRunCommand(tmpDir, 'app.py');
      expect(result).toBe('python app.py');
    });

    it('should return python -m command when src directory exists', () => {
      // Create src directory to simulate existing project
      fs.mkdirSync(path.join(tmpDir, 'src'), { recursive: true });

      const result = plugin.getRunCommand(tmpDir);
      // Should use basename of cwd converted to package name
      const expectedPkgName = path.basename(tmpDir).replace(/[^a-zA-Z0-9_-]/g, '').replace(/-+/g, '_');
      expect(result).toBe(`python -m ${expectedPkgName}`);
    });

    it('should return python main.py when no src directory exists', () => {
      const result = plugin.getRunCommand(tmpDir);
      expect(result).toBe('python main.py');
    });
  });

  describe('getTestCommand()', () => {
    it('should return pytest', () => {
      const result = plugin.getTestCommand(tmpDir);
      expect(result).toBe('pytest');
    });
  });
});
